pluginManagement {
    // Runs before Gradle configures projects.
    includeBuild('settings-logic')
    // Runs after settings and is used to configure projects.
    includeBuild 'build-logic'

    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'bento.analysis.ben-manes-versions-settings'
    id 'bento.analysis.dagp-settings'
    id 'bento.report.aggregation-settings'
}

dependencyResolutionManagement {
    includeBuild 'build-logic'

    repositories {
        mavenCentral()
    }
}

rootProject.name = 'bento-fx'

enableFeaturePreview('STABLE_CONFIGURATION_CACHE')
enableFeaturePreview('TYPESAFE_PROJECT_ACCESSORS')

include 'platform'
include 'report-aggregation'

include 'core'

include 'demos:basic'
