plugins {
    alias(libs.plugins.javafx)
    id 'bento.project.project-convention'
    id 'bento.release.publish-convention'
}

description = "BentoFX Persistence for JSON"

javafx {
    modules = ['javafx.controls', 'javafx.graphics']
    configurations = ['compileOnly']
}

dependencies {

    api projects.persistence.api

    implementation projects.persistence.codec.common

    implementation libs.jackson.annotations
    implementation libs.jackson.databind

    testImplementation testFixtures(projects.persistence.testFixtures)

    testImplementation libs.javafx.graphics
}
