pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
    }
    versionCatalogs {
        libs {
            from(files('../gradle/libs.versions.toml'))
        }
    }
}

rootProject.name = 'build-logic'
