plugins {
    alias(libs.plugins.javafx)
    id 'bento.project.project-convention'
    id 'bento.release.publish-convention'
    id 'bento.test.functional-test-suite'
}

description = "BentoFX Persistence API"

javafx {
    modules = ['javafx.base', 'javafx.controls', 'javafx.graphics']
    configurations = ['api','functionalTestImplementation']
}

dependencies {
    api projects.core

    implementation libs.slf4j.api

    testImplementation testFixtures(projects.persistence.testFixtures)

    functionalTestImplementation testFixtures(projects.persistence.testFixtures)

    functionalTestRuntimeOnly libs.slf4j.simple
}
