pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
    versionCatalogs {
        libs {
            from(files('../gradle/libs.versions.toml'))
        }
    }
}

rootProject.name = 'settings-logic'
