[versions]
# noinspection UnusedVersionCatalogEntry
bentofx = "0.16.0"
# noinspection UnusedVersionCatalogEntry
gradle-wrapper = "9.6.1"
# noinspection UnusedVersionCatalogEntry
gradle-checksum = "9c0f7faeeb306cb14e4279a3e084ca6b596894089a0638e68a07c945a32c9e14"
# noinspection UnusedVersionCatalogEntry
java-jdk = "21"

# Libraries
assertj = "4.0.0-M1"
javafx = "26.0.2"
jspecify = "1.0.0"
junit = "6.1.2"
testfx = "4.0.18"
testfx-monocle = "21.0.2"

# Plugins
buildconfig = "6.0.10"
javafx-plugin = "0.1.0"
jreleaser = "1.25.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
javafx-base = { module = "org.openjfx:javafx-base", version.ref = "javafx" }
javafx-controls = { module = "org.openjfx:javafx-controls", version.ref = "javafx" }
javafx-gradlePlugin-dependency = { module = "org.openjfx.javafxplugin:org.openjfx.javafxplugin.gradle.plugin", version.ref = "javafx-plugin" }
javafx-graphics = { module = "org.openjfx:javafx-graphics", version.ref = "javafx" }
jreleaser-gradlePlugin-dependency = { module = "org.jreleaser:org.jreleaser.gradle.plugin", version.ref = "jreleaser" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params" }
testfx = { module = "org.testfx:testfx-junit5", version.ref = "testfx" }
testfx-core = { module = "org.testfx:testfx-core", version.ref = "testfx" }
testfx-monocle = { module = "org.testfx:openjfx-monocle", version.ref = "testfx-monocle" }

[bundles]
annotations = ["jspecify"]
javafx = [ "javafx-base", "javafx-controls", "javafx-graphics", ]
test-libraries = ["assertj", "junit-api",  "junit-params", "testfx", "testfx-core","testfx-monocle"]
test-runtime = ["junit-engine", "junit-launcher"]

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
javafx = { id = "org.openjfx.javafxplugin", version.ref = "javafx-plugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
