[versions]
# noinspection UnusedVersionCatalogEntry
maven-group = "software.coley.bento-fx"
# noinspection UnusedVersionCatalogEntry
bentofx = "0.16.1-SNAPSHOT"
# noinspection UnusedVersionCatalogEntry
gradle-wrapper = "9.7.1"
# noinspection UnusedVersionCatalogEntry
gradle-checksum = "acd53f1edaf02f1a8ff99879f8a34b302661a057d9b063ae9e35b552f804d20a"
# noinspection UnusedVersionCatalogEntry
java-jdk = "21"

# Libraries
assertj = "4.0.0-M1"
errorprone = "2.50.0"
javafx = "21.0.12"
jspecify = "1.0.1"
junit = "6.1.2"
nullaway = "0.13.8"
testfx = "4.0.18"
testfx-monocle = "21.0.2"

# Plugins
ben-manes-versions-plugin = "0.56.0"
buildconfig = "6.0.10"
dependency-analysis-gradle-plugin = "3.17.0"
errorprone-plugin = "5.1.0"
# noinspection UnusedVersionCatalogEntry
jacoco = "0.8.15"
javafx-plugin = "0.1.0"
jreleaser = "1.25.0"
nullaway-plugin = "3.1.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
ben-manes-versions-gradlePlugin-dependency = { module = "com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin", version.ref = "ben-manes-versions-plugin" }
dependencyAnalysis-buildHealth-gradlePlugin-dependency = { module = "com.autonomousapps.build-health:com.autonomousapps.build-health.gradle.plugin", version.ref = "dependency-analysis-gradle-plugin" }
dependencyAnalysis-gradlePlugin-dependency = { module = "com.autonomousapps.dependency-analysis:com.autonomousapps.dependency-analysis.gradle.plugin", version.ref = "dependency-analysis-gradle-plugin" }
# noinspection UnusedVersionCatalogEntry
errorprone = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
errorprone-gradlePlugin-dependency = { module = "net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin", version.ref = "errorprone-plugin" }
javafx-base = { module = "org.openjfx:javafx-base", version.ref = "javafx" }
javafx-controls = { module = "org.openjfx:javafx-controls", version.ref = "javafx" }
javafx-gradlePlugin-dependency = { module = "org.openjfx.javafxplugin:org.openjfx.javafxplugin.gradle.plugin", version.ref = "javafx-plugin" }
javafx-graphics = { module = "org.openjfx:javafx-graphics", version.ref = "javafx" }
jreleaser-gradlePlugin-dependency = { module = "org.jreleaser:org.jreleaser.gradle.plugin", version.ref = "jreleaser" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
# noinspection UnusedVersionCatalogEntry
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
nullaway-gradlePlugin-dependency = { module = "net.ltgt.nullaway:net.ltgt.nullaway.gradle.plugin", version.ref = "nullaway-plugin" }
testfx = { module = "org.testfx:testfx-junit5", version.ref = "testfx" }
testfx-core = { module = "org.testfx:testfx-core", version.ref = "testfx" }
testfx-monocle = { module = "org.testfx:openjfx-monocle", version.ref = "testfx-monocle" }

[bundles]
annotations = ["jspecify"]
javafx = [ "javafx-base", "javafx-controls", "javafx-graphics", ]
test-libraries = ["assertj", "testfx", "testfx-core", "testfx-monocle"]

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
# noinspection UnusedVersionCatalogEntry
dependencyAnalysis-buildHealth = { id = "com.autonomousapps.build-health", version.ref = "dependency-analysis-gradle-plugin" }
# noinspection UnusedVersionCatalogEntry
dependencyAnalysis-gradlePlugin = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependency-analysis-gradle-plugin" }
# noinspection UnusedVersionCatalogEntry
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
javafx = { id = "org.openjfx.javafxplugin", version.ref = "javafx-plugin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
# noinspection UnusedVersionCatalogEntry
nullaway = { id = "net.ltgt.nullaway", version.ref = "nullaway-plugin" }
