plugins {
    id 'java-platform'
    id 'bento.release.publish-convention'
}

javaPlatform {
    allowDependencies()
}

group = libs.versions.maven.group.get()
version = libs.versions.bentofx.get()
description = 'BentoFX Platform BOM'

// See also Gradle Version Catalog at '<root>\gradle\libs.versions.toml'.
dependencies {
    /*
     * BOMs
     *
     * Ordering matters! Declaring a BOM before subsequent platform declarations
     * will cause third-party dependencies declared in the BOM to be overridden
     * by those platform declarations.
     */

    api platform(libs.junit.bom.get())

    constraints {
        api libs.bundles.javafx
        api libs.bundles.test.libraries
        api libs.bundles.annotations
    }
}
