import software.coley.gradle.lifecycle.TestLifecycle

import static org.gradle.language.base.plugins.LifecycleBasePlugin.VERIFICATION_GROUP
import static software.coley.gradle.lifecycle.BuildLifecycle.ALL_CLASSES_TASK_NAME

plugins {
    id 'jacoco'
    id 'bento.project.build-lifecycle'
    id 'bento.test.test-lifecycle'
    id 'com.autonomousapps.dependency-analysis'
    id 'jvm-test-suite'
}

def testSuiteName = 'test'
def jacocoEnabled = TestLifecycle.enableJacoco(project)
def testTask = tasks.named(testSuiteName, Test)
def testClassesTask = tasks.named('testClasses')
def jacocoTestReportTask = tasks.named('jacocoTestReport', JacocoReport) { reportTask ->
    reportTask.group = VERIFICATION_GROUP
    reportTask.description = 'Generates JaCoCo coverage report for the test task.'
    reportTask.shouldRunAfter(testTask)
    reportTask.reports {
        xml.required = true
        html.required = true
        csv.required = false
    }
}
def checkTask = tasks.named('check')
def allClassesTask = tasks.named(ALL_CLASSES_TASK_NAME)

dependencies {
    def versionCatalog = versionCatalogs.named('libs')
    add("${testSuiteName}CompileOnly", versionCatalog.findBundle('annotations').get())
    add("${testSuiteName}Implementation", versionCatalog.findBundle('test-libraries').get())
    add("${testSuiteName}RuntimeOnly", versionCatalog.findBundle('test-runtime').get())
}

dependencyAnalysis {
    abi {
        exclusions {
            excludeSourceSets(testSuiteName)
        }
    }
    // Test source set analysis broken by Kotlin 2.0.20:
    // https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1239
    issues {
        ignoreSourceSet(testSuiteName)
    }
}

allClassesTask.configure {
    dependsOn(testClassesTask)
}

checkTask.configure {
    dependsOn(testTask)
    if (jacocoEnabled) {
        dependsOn(jacocoTestReportTask)
    }
}
