import static org.gradle.language.base.plugins.LifecycleBasePlugin.VERIFICATION_GROUP
import static software.coley.gradle.lifecycle.TestLifecycle.*

plugins {
    id 'base'
}

def checkTask = tasks.named('check')

def checkIntegrationTask = tasks.register(CHECK_INTEGRATION_TASK_NAME) {
    description = 'Runs integration tests for all applicable subprojects.'
    group = VERIFICATION_GROUP
    shouldRunAfter(checkTask)
}

tasks.register(CHECK_ALL_TASK_NAME) {
    description = 'Runs all tests for all applicable subprojects.'
    group = VERIFICATION_GROUP
    dependsOn(checkTask)
    dependsOn(checkIntegrationTask)
}
