plugins {
    alias(libs.plugins.javafx)
    id 'bento.project.project-convention'
    id 'bento.release.publish-convention'
}

description = 'BentoFX Persistence for XML'

javafx {
    modules = ['javafx.graphics']
    configurations = ['implementation']
}

dependencies {

    api projects.persistenceCore

    implementation projects.persistence.codec.common

    implementation libs.jackson.annotations
    implementation libs.jackson.databind
    implementation libs.jackson.xml

    testImplementation testFixtures(projects.persistence.testFixtures)
}
