plugins {
    alias(libs.plugins.javafx)
    id 'bento.project.project-convention'
    id 'bento.project.application-convention'
}

description = 'BentoFX Basic Demo'

application {
    applicationName = description ?: name
    mainModule = 'bento.fx.demo.basic'
    mainClass = 'demo.Runner'
    applicationDefaultJvmArgs = ["-Xms256m", "-Xmx1024m"]
}

javafx {
    modules = ['javafx.base', 'javafx.controls', 'javafx.graphics']
}

dependencies {
    implementation projects.core

}
